
import java.awt.CardLayout;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */
public class View1 extends JFrame {
String cookie = "";
String pinNum = "";
    /**
     * Creates new form View1
     */
    public View1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        loginView = new javax.swing.JPanel();
        userNameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        register = new javax.swing.JButton();
        playGameView = new javax.swing.JPanel();
        startNewGame = new javax.swing.JButton();
        joinAGame = new javax.swing.JButton();
        startGameView = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        keyTextField = new javax.swing.JTextField();
        participantsTextField = new javax.swing.JTextField();
        start = new javax.swing.JButton();
        joinGameView = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        enterKey = new javax.swing.JTextField();
        joinGame = new javax.swing.JButton();
        waitingView = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        suggestionView = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        whatIsTheWordFor = new javax.swing.JTextField();
        youtSuggestion = new javax.swing.JTextField();
        submitSuggestion = new javax.swing.JButton();
        optionView = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        button1 = new javax.swing.JRadioButton();
        button2 = new javax.swing.JRadioButton();
        button3 = new javax.swing.JRadioButton();
        submitOption = new javax.swing.JButton();
        resultView = new javax.swing.JPanel();
        roundResult = new javax.swing.JTextField();
        overallResult = new javax.swing.JTextField();
        nextRound = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        topLabel = new javax.swing.JLabel();
        buttomPanel = new javax.swing.JPanel();
        buttomLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FoilMaker!");
        setResizable(false);

        main.setLayout(new java.awt.CardLayout());

        userNameLabel.setText("Username:");

        passwordLabel.setText("Password:");

        userNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextFieldActionPerformed(evt);
            }
        });

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginViewLayout = new javax.swing.GroupLayout(loginView);
        loginView.setLayout(loginViewLayout);
        loginViewLayout.setHorizontalGroup(
            loginViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginViewLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(loginViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loginViewLayout.createSequentialGroup()
                        .addGroup(loginViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userNameLabel)
                            .addComponent(passwordLabel))
                        .addGap(18, 18, 18)
                        .addGroup(loginViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loginViewLayout.createSequentialGroup()
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        loginViewLayout.setVerticalGroup(
            loginViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginViewLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(loginViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(loginViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login)
                    .addComponent(register))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        main.add(loginView, "card3");

        startNewGame.setText("Start New Game");
        startNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startNewGameActionPerformed(evt);
            }
        });

        joinAGame.setText("Join a Game");
        joinAGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinAGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout playGameViewLayout = new javax.swing.GroupLayout(playGameView);
        playGameView.setLayout(playGameViewLayout);
        playGameViewLayout.setHorizontalGroup(
            playGameViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playGameViewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(joinAGame, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        playGameViewLayout.setVerticalGroup(
            playGameViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playGameViewLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(playGameViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startNewGame)
                    .addComponent(joinAGame))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        main.add(playGameView, "playGame");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel2.setText("Others should use this key to join your game");

        keyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyTextFieldActionPerformed(evt);
            }
        });

        participantsTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Participants"));
        participantsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participantsTextFieldActionPerformed(evt);
            }
        });

        start.setText("Start Game");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout startGameViewLayout = new javax.swing.GroupLayout(startGameView);
        startGameView.setLayout(startGameViewLayout);
        startGameViewLayout.setHorizontalGroup(
            startGameViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startGameViewLayout.createSequentialGroup()
                .addGroup(startGameViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startGameViewLayout.createSequentialGroup()
                        .addGroup(startGameViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(startGameViewLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(startGameViewLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(keyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(startGameViewLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(participantsTextField)))
                .addContainerGap())
            .addGroup(startGameViewLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(start)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        startGameViewLayout.setVerticalGroup(
            startGameViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startGameViewLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(participantsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(start)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main.add(startGameView, "startGame");

        jLabel3.setText("Enter the game key to join a game");

        enterKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterKeyActionPerformed(evt);
            }
        });

        joinGame.setText("Join Game");
        joinGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout joinGameViewLayout = new javax.swing.GroupLayout(joinGameView);
        joinGameView.setLayout(joinGameViewLayout);
        joinGameViewLayout.setHorizontalGroup(
            joinGameViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joinGameViewLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(joinGameViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, joinGameViewLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, joinGameViewLayout.createSequentialGroup()
                        .addComponent(joinGame, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, joinGameViewLayout.createSequentialGroup()
                        .addComponent(enterKey, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );
        joinGameViewLayout.setVerticalGroup(
            joinGameViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joinGameViewLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(enterKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(joinGame, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        main.add(joinGameView, "joinGame");

        jLabel4.setText("Waiting for leader ...");

        javax.swing.GroupLayout waitingViewLayout = new javax.swing.GroupLayout(waitingView);
        waitingView.setLayout(waitingViewLayout);
        waitingViewLayout.setHorizontalGroup(
            waitingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, waitingViewLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(71, 71, 71))
        );
        waitingViewLayout.setVerticalGroup(
            waitingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waitingViewLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel4)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        main.add(waitingView, "waiting");

        jLabel1.setText("What is the word for");

        whatIsTheWordFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whatIsTheWordForActionPerformed(evt);
            }
        });

        youtSuggestion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Your Suggestion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        submitSuggestion.setText("Submit Suggestion");

        javax.swing.GroupLayout suggestionViewLayout = new javax.swing.GroupLayout(suggestionView);
        suggestionView.setLayout(suggestionViewLayout);
        suggestionViewLayout.setHorizontalGroup(
            suggestionViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suggestionViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(suggestionViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(youtSuggestion)
                    .addComponent(whatIsTheWordFor)
                    .addGroup(suggestionViewLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(suggestionViewLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(submitSuggestion, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        suggestionViewLayout.setVerticalGroup(
            suggestionViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suggestionViewLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(whatIsTheWordFor, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(youtSuggestion, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(submitSuggestion)
                .addGap(16, 16, 16))
        );

        main.add(suggestionView, "suggestion");

        jLabel5.setText("Pick your option below");

        submitOption.setText("Sumit Option");

        javax.swing.GroupLayout optionViewLayout = new javax.swing.GroupLayout(optionView);
        optionView.setLayout(optionViewLayout);
        optionViewLayout.setHorizontalGroup(
            optionViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionViewLayout.createSequentialGroup()
                .addGroup(optionViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionViewLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(optionViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button3)
                            .addComponent(button2)
                            .addComponent(button1)
                            .addComponent(jLabel5)))
                    .addGroup(optionViewLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(submitOption, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        optionViewLayout.setVerticalGroup(
            optionViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionViewLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addGap(83, 83, 83)
                .addComponent(button1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button3)
                .addGap(55, 55, 55)
                .addComponent(submitOption)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        main.add(optionView, "option");

        roundResult.setBorder(javax.swing.BorderFactory.createTitledBorder("Round Result"));

        overallResult.setBorder(javax.swing.BorderFactory.createTitledBorder("Overall Results"));

        nextRound.setText("Next Round");

        javax.swing.GroupLayout resultViewLayout = new javax.swing.GroupLayout(resultView);
        resultView.setLayout(resultViewLayout);
        resultViewLayout.setHorizontalGroup(
            resultViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultViewLayout.createSequentialGroup()
                .addGroup(resultViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resultViewLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(resultViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(overallResult, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(roundResult)))
                    .addGroup(resultViewLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(nextRound, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        resultViewLayout.setVerticalGroup(
            resultViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultViewLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(roundResult, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(overallResult, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nextRound)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        main.add(resultView, "result");

        topLabel.setText("FoilMaker!");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(topLabel)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttomLabel.setText("New User Created");

        javax.swing.GroupLayout buttomPanelLayout = new javax.swing.GroupLayout(buttomPanel);
        buttomPanel.setLayout(buttomPanelLayout);
        buttomPanelLayout.setHorizontalGroup(
            buttomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttomLabel)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        buttomPanelLayout.setVerticalGroup(
            buttomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttomPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(buttomLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(277, 467));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextFieldActionPerformed

    private void whatIsTheWordForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whatIsTheWordForActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_whatIsTheWordForActionPerformed

    private void startNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startNewGameActionPerformed
        // TODO add your handling code here:
        String a = "STARTNEWGAME--"+cookie;
        String b = sendserver(a);
        
        if(b.contains("USERNOTLOGGEDIN")){
            JOptionPane.showMessageDialog(null,"Invalid User Token");
        }
        else if(b.contains("FAILURE")){
            JOptionPane.showMessageDialog(null,"Internal Error");
        }
        else if(b.contains("SUCCESS")){
            boolean click = false;
            keyTextField.setEditable(false);
            
            pinNum = b.substring(b.length()-3,b.length());
            CardLayout card = (CardLayout)main.getLayout();
            card.show(main,"startGame");
            buttomLabel.setText("Press <Start game> to start game");
            start.setEnabled(false);
            keyTextField.setText(pinNum);
           
            while(click == false){
                String b = sendserver2();
                String 
            }
        }

    }//GEN-LAST:event_startNewGameActionPerformed

    private void joinAGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinAGameActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)main.getLayout();
        card.show(main,"joinGame");
    }//GEN-LAST:event_joinAGameActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        String a = "LOGIN--"+userNameTextField.getText()+ "--"+jPasswordField.getPassword();
        String b = sendserver(a);
       
        if(b.contains("INVALIDMESSAGEFORMAT")){
            JOptionPane.showMessageDialog(null, "Invalid Message Formate!");
        }
        else if(b.contains("UNKNOWNUSER")){
            JOptionPane.showMessageDialog(null, "Unknown User");
        }
        else if(b.contains("INVALIDUSERPASSWORD")){
            JOptionPane.showMessageDialog(null, "Invalid User Password");
        }
        else if(b.contains("USERALREADYLOGIN")){
            JOptionPane.showMessageDialog(null, "User Already Login");
        }
        else if(b.contains("SUCCESS")){
            cookie = b.substring(26,b.length());
        CardLayout card = (CardLayout)main.getLayout();
        card.show(main,"playGame");
        topLabel.setText(userNameTextField.getText());
        buttomLabel.setText("Welcome!");
        
        }
        
    }//GEN-LAST:event_loginActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        String a = "CREATENEWUSER--" + userNameTextField.getText()+ "--"+jPasswordField.getPassword();
        String b = sendserver(a);
        
        if(b.contains("INVALIDMESSAGEFORMAT")){
            JOptionPane.showMessageDialog(null, "Invalid Message Formate!");
        }
        else if(b.contains("UNKNOWNUSER")){
            JOptionPane.showMessageDialog(null, "Unknown User");
        }
        else if(b.contains("INVALIDUSERPASSWORD")){
            JOptionPane.showMessageDialog(null, "Invalid User Password");
        }
        else if(b.contains("USERALREADYEXISTS")){
            JOptionPane.showMessageDialog(null, "User Already Exists");
        }
        else if(b.contains("SUCCESS")){
        CardLayout card = (CardLayout)main.getLayout();
        card.show(main,"playGame");
        //topLabel.setText(name);
        buttomLabel.setText("Welcome!");
        }
    }//GEN-LAST:event_registerActionPerformed

    private void joinGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinGameActionPerformed
        // TODO add your handling code here:
        String a = "JOINGAME--"+cookie+"--"+enterKey.getText();
        String b =sendserver(a);
        if(b.contains("USERNOTLOGGEDIN")){
            JOptionPane.showMessageDialog(null,"User Not Logged In");
        }
        else if(b.contains("GAMEKEYNOTFOUND")){
            JOptionPane.showMessageDialog(null,"Game Key Word Not Found");
        }
        else if(b.contains("FAILURE")){
            JOptionPane.showMessageDialog(null,"User Already Playing The Game");
        }
        else if(b.contains("SUCCESS")){
            CardLayout card = (CardLayout)main.getLayout();
            card.show(main,"waiting");
            buttomLabel.setText("Joined game: waiting for the leader");
        }
        
    }//GEN-LAST:event_joinGameActionPerformed

    private void participantsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participantsTextFieldActionPerformed
        // TODO add your handling code here:
        while()
        
    }//GEN-LAST:event_participantsTextFieldActionPerformed

    private void keyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyTextFieldActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_keyTextFieldActionPerformed

    private void enterKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterKeyActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        
        String a = "ALLPARTICIPANTSHAVEJOINED--"+cookie+pinNum;
        String b = sendserver(a);
        
        if(b.contains("USERNOTLOGGEDIN")){
            JOptionPane.showMessageDialog(null,"Invalid user token");
        }
        else if(b.contains("INVALIDGAMETOKEN")){
            JOptionPane.showMessageDialog(null,"Invalid game token");
        }
        else if(b.contains("USERNOTGAMELEADER")){
            JOptionPane.showMessageDialog(null,"User already playing the game");
        }
        else{
            CardLayout card = (CardLayout)main.getLayout();
            card.show(main,"suggestion");
            buttomLabel.setText("Joined game: waiting for the leader");
        }
        
        
    }//GEN-LAST:event_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttomLabel;
    private javax.swing.JPanel buttomPanel;
    private javax.swing.JRadioButton button1;
    private javax.swing.JRadioButton button2;
    private javax.swing.JRadioButton button3;
    private javax.swing.JTextField enterKey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JButton joinAGame;
    private javax.swing.JButton joinGame;
    private javax.swing.JPanel joinGameView;
    private javax.swing.JTextField keyTextField;
    private javax.swing.JButton login;
    private javax.swing.JPanel loginView;
    private javax.swing.JPanel main;
    private javax.swing.JButton nextRound;
    private javax.swing.JPanel optionView;
    private javax.swing.JTextField overallResult;
    private javax.swing.JTextField participantsTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel playGameView;
    private javax.swing.JButton register;
    private javax.swing.JPanel resultView;
    private javax.swing.JTextField roundResult;
    private javax.swing.JButton start;
    private javax.swing.JPanel startGameView;
    private javax.swing.JButton startNewGame;
    private javax.swing.JButton submitOption;
    private javax.swing.JButton submitSuggestion;
    private javax.swing.JPanel suggestionView;
    private javax.swing.JLabel topLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JPanel waitingView;
    private javax.swing.JTextField whatIsTheWordFor;
    private javax.swing.JTextField youtSuggestion;
    // End of variables declaration//GEN-END:variables
}
